### ISSUE TITLE
Mail not working : typing mistake in contact email 

### ISSUE THREAD

**Issue by altafkhan098** [tanbirali/tanbirali#1]
#### Description
We have encountered an issue related to the contact email specified in our project. After a review of our email functionality, it appears that there is a typo in the contact email address, which is causing emails to fail to deliver.

#### Suggested Fix
Please review and correct the contact email address in the codebase. Ensure that the correct email address is implemented to allow for successful email delivery.

![screenshot-1725731171543](https://github.com/user-attachments/assets/3395edf8-a920-48a1-bb84-0bb7821ae8d5)

Thank you for looking into this issue!

**Comment by tanbirali** [comment]
I think there is a misunderstanding, the mail does work and it redirects you to open your mail to send mail to the given email address,

**Comment by altafkhan098** [comment]
I think there is a misunderstanding, the spelling of the **Gmail** is wrong.
